[package]
name = "foldry-application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
foldry-core = { path = "../foldry-core" }
jiff.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
ts-rs.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
